services:

  llm-debater:

    container_name: llm-debater
    build: .
    ports:
      - "${APP_PORT:-8505}:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    command: streamlit run app.py --server.runOnSave=true --server.fileWatcherType=poll
